### ISSUE TITLE
Sorting and paging

### ISSUE THREAD

**Issue by joebordes** [Mevrael/bunny#14]
I am testing the sorting option on the datatable. The datatable I am using has pagination.
When I click on the column header to sort I get the correct call, but once the table is sorted and I click the pagination to move to another page I lose the search parameters.

Do I have to do something with the Pagination configuration to get it to respect the sorting conditions established?

**Comment by Mevrael** [comment]
I believe it is because Pagination link urls are not updated. Will check it on next update.

**Comment by joebordes** [comment]
ok

**Comment by Mevrael** [comment]
Fixed in 0.13.0
