### ISSUE TITLE
introduce a changelog

### ISSUE THREAD

**Issue by skwakman** [Mevrael/bunny#17]
Hi!

Currently it's hard to find out what things have changed between BunnyJS versions and if a new version introduced a breaking change. Perhaps it's a good idea to introduce a changelog file?

**Comment by Mevrael** [comment]
Hi @skwakman

Thank you for your interest in BunnyJS and feedback.

You are absolutely right. In the ideal situation every release should be released with a tags and a full changelog description, however, it requires much more human resources I have right now. So making a simple CHANGELOG.md probably for now would be a good idea.

However, it would be great if you could help me understand which components are used by community and requires a changelog on the first place. Regarding all the components which already have official examples and/or documentation - they don't receive any critical changes, so it is important for me to know on which other components/helpers I should focus first when writing changelog.


Thanks again, if you will have some time to share your experience with BunnyJS, codebase and architecture so far, it would be great and could help making this product better and simpler for everyone.

**Comment by skwakman** [comment]
Hi @Mevrael,

Currently I'm only using BunnyJS' form validation components, however other user might want to know about changes in different components as well. 

My primary concern here is finding out what changed between BunnyJS versions so I can test if my usage of these components won't break anything. Although non-critical changes _should_ not introduce any bugs, there's always that one use case that nobody thought of.

In future updates, a short per-version overview of which components were changed and if the changes should not break anything should suffice. If you're using github's issue tracking, a (auto-generated?) list of closed issues per version could work as well.

**Comment by Mevrael** [comment]
Thank you for comments.

If there are any important changes in the already documented components then they are obligatory posted on my Twitter account or in GitHub release message.

Regarding Form Validation component please take into account this post https://twitter.com/Mevrael/status/820678938838102017 (I will also post a release note what needs to be changed when I will have time to update those classes in default settings)

Please follow me on Twitter to receive all the important information regarding the upcoming changes in BunnyJS as well. You also may join and follow our Gitter channel https://gitter.im/bunny-js/Lobby
