### ISSUE TITLE
Ignore input

### ISSUE THREAD

**Issue by zslabs** [Mevrael/bunny#19]
Is there an option to ignore certain inputs? With components like https://github.com/jshjohnson/Choices that may create additional form inputs to interact with them, I need control to ignore the `<input>` created to search lists.

**Comment by Mevrael** [comment]
Bunny Validation does only what you want from each input by using HTML5 validation and custom attributes like `required`.

So far you are not adding those attributes, you are removing any possibility of that input from being marked as invalid.

What I see from the Choices component is that they are adding inputs manually, but there are no any validation attributes used, so Bunny Form Validation will ignore them already.

**Comment by zslabs** [comment]
Awesome, thanks for confirming!
