### ISSUE TITLE
Example datatables

### ISSUE THREAD

**Issue by nenad007** [Mevrael/bunny#2]
Hello, can you show a example of a datatable?

**Comment by Mevrael** [comment]
Hi, @nenad007

Because of lack of free time I am usually working on BunnyJS on weekends, so tomorrow I will make some another updates to code and website.

Since you are interested in datatables, I will post an example tomorrow.

Which functions are you expecting from datatables, what is your use case, requirements? What is your technology stack?

**Comment by nenad007** [comment]
Hi @Mevrael 

Thank you, that will be great.

I'm looking for the usual functionality as Pagination, sure Sort/Filter (with Callback) will be nice to have but without is OK too, as it comes without jQuery depedency. 

I plan to use it where ever I show a List of data. My technology stack client side: HTML5, CSS, JavaScript and server side: PHP, MySQL.

**Comment by Mevrael** [comment]
@nenad007 Here we go https://bunnyjs.com/examples/datatable/

Pagination is exactly what it does very well.

I am planning adding filtering in future. On server if you are using Laravel you can just use `->paginate(10)` on your model.

I believe we can keep this issue open for any questions or comments about DataTable.

Please let me know how easy it was for you to make Bunny DataTable running in your code and any feedback about the configuration using custom tags, attributes and other processes.

P.S. for large tables may be you would like to use `Element.scrollTo()` from `src/bunny.element` on `DataTable.onRedraw()` to add smooth scrolling to the top of table or page whenever table's page is changed.

**Comment by Mevrael** [comment]
Hi @nenad007 

In latest update search functionality added. More information in https://github.com/Mevrael/bunny/issues/11#issuecomment-266311168
