### ISSUE TITLE
Email validation is case sensitive

### ISSUE THREAD

**Issue by adamseabrook** [Mevrael/bunny#21]
https://bunnyjs.com/examples/form-validation/ I ran a few tests here and these emails fail to validate:
USER@domain.com
useR@domain.com
user@Domain.com
user@DOMAIN.com
user@domain.Com
user@domain.COM

**Comment by Mevrael** [comment]
Thank you for your interest in BunnyJS and bug report.

`i` option for email RegExp has been added.

Please feel free to join our Gitter as well https://gitter.im/bunny-js/Lobby
