### ISSUE TITLE
Basic checkbox required validation doesn't seem to work

### ISSUE THREAD

**Issue by StevenVerbiest** [Mevrael/bunny#26]
See JSFiddle:

https://jsfiddle.net/oc0veLLp/3/

The required error is always thrown, even when the checkbox is actually checked.

I am only including
- babel-helpers.js
- element.js
- validation.js

Am I doing something wrong? Did I forget to include a js file? Or is this actually a bug?

**Comment by Mevrael** [comment]
You have `value=""` which makes your checkbox useless. Either remove value and let browser set it to default value which is `on` or set some value like 1 yourself.

Inputs with empty value are not validated as per spec. It is the same as having option in select with empty value.

**Comment by StevenVerbiest** [comment]
That fixed the issue. Thanks!
