### ISSUE TITLE
Validation preSubmit and isValid method

### ISSUE THREAD

**Issue by andtankian** [Mevrael/bunny#31]
What's up guys?

I couldn't found neither in docs or source code a way to verify if the form is valid.

In fact, I need to do extra things before properly submit the form (like sanitize inputs, made some animations, etc.)

Today, is it possible? Am I missing some method here? 

If not, I suggest to implement these methods. It would be very interesting to have these.

Thank you very much.

**Comment by Mevrael** [comment]
Hi @andtankian 

I believe you are well.

The first docs for BunnyJS are Web Standards.

You can check if form is valid with native `form.checkValidity()` and you can listen for `submit` event and add `event.preventDefault()` to cancel form submission within event listener.

Cheers

**Comment by andtankian** [comment]
Thank you for replying.

I really could prevent default behavior in my own custom submit event handler.

I should warn that `event.preventDefault()` for itself doesn't stop the propagation, for this, we should call `event.stopImmediatePropagation()` to prevent the [handler binded in the init function](https://github.com/Mevrael/bunny/blob/master/src/Validation.js#L594) to be executed when [init function invoke the `form.submit()`](https://github.com/Mevrael/bunny/blob/master/src/Validation.js#L605).

I really appreciate your help.

Thanks.

**Comment by andtankian** [comment]
Thank you for replying.

The problem I'm having is about the [Validation form submit event handler](https://github.com/Mevrael/bunny/blob/master/src/Validation.js#L605) that is calling `form.submit()`. So doesn't matter if I `event.preventDefault()` cause although submit event handler is successfully prevented in my custom handler, the Validation form submit event handler is still invoked again.
For obvious reasons, browsers prevent these handlers to be executed eternally, so the submit is actually done regardless of my custom prevent default.

Do you have any ideas?

Thank you very much.

**Comment by Mevrael** [comment]
Thank you for notes.

Well, I suppose easiest option in that case would be to add onSubmit(form, promise / callback) method into Validation component and adjust init(). If it's a promise, wait till it's fulfilled. If it's a function, run it immediately.

In that case you could add additional actions before form is submitted like animations and you won't need to worry about checking if form is valid since it already is done for you inside if in init().

I am currently unavailable to do so. Maybe you could submit this commit and I would later push it to NPM.

Cheers

**Comment by juniorgarcia** [comment]
By now I'm also not able to perform a validation and send the form via Ajax when form is valid due this implementation detail. Also I didn't understand what you meant on
> [...] add onSubmit(form, promise / callback) method into Validation component and adjust init().

`preventDefault();` didn't work in any way.

I've searched on source code but didn't find references to this `onSubmit` method.
