### ISSUE TITLE
js-yaml security vulnerability

### ISSUE THREAD

**Issue by NHKK** [Mevrael/bunny#34]
Please update the dependencies as it is bringing in a vulnerable version of js-yaml. I'm not sure how to fix.
<img width="689" alt="Screen Shot 2019-05-18 at 11 59 34 AM" src="https://user-images.githubusercontent.com/18389319/57972124-7188ec00-7964-11e9-9aed-494a38f56ba7.png">
<img width="722" alt="Screen Shot 2019-05-18 at 12 00 09 PM" src="https://user-images.githubusercontent.com/18389319/57972129-85345280-7964-11e9-8694-a13d187049d4.png">

**Comment by Mevrael** [comment]
I have updated assets-builder dependencies and also removed assets-builder from bunnyjs dependencies so it would install BunnyJS itself faster.

Please update bunnyjs to 0.14.42 and let me know if you still will have any issues.

**Comment by NHKK** [comment]
Thanks it works
